#!/bin/bash

INTERFACE=$1
COMMAND=$2

export DOCKER_IP=$(ip -4 addr show $INTERFACE | grep -Po 'inet \K[\d.]+')
echo $DOCKER_IP

if [[ $(docker network ls --filter="name=valet" -q) == "" ]]; then
  docker network create valet
fi

if [[ ! -e /etc/resolvconf/resolv.conf.d/tail || "$(grep $DOCKER_IP /etc/resolvconf/resolv.conf.d/tail)" == "" ]]; then
  sudo mkdir -p /etc/resolvconf/resolv.conf.d
  cat <<RESOLVER_EOF | sudo tee /etc/resolvconf/resolv.conf.d/tail
nameserver $DOCKER_IP
RESOLVER_EOF
fi

docker-compose "$COMMAND" -d
